### PR TITLE
PalindromeCheck.cpp 

### PR DESCRIPTION
**Pull request by abhilashkpy**
Simple C++ program to check if a number is Palindrome or not.

### CODE REVIEW

**Comment by Rasesh2005** [comment]
You Didnt Remove the MENUDRIVENSTACK file , remove it and then push it so i will merge it

**Comment by abhilashkpy** [comment]
Deleted the STL containing file and updated the repository.

**Comment by abhilashkpy** [comment]
Program to check for a number for Palindrome or not.

**Comment by Rasesh2005** [comment]
You need to make the main code as a function and call in inside the main function…

**Comment by abhilashkpy** [comment]
Updates made:  Main code being created as a function and being called from inside the main() function.

**Pull request merged**
