### PR TITLE
Added Euclid's GCD

### PR DESCRIPTION
**Pull request by Adarsh08X**
Added Euclid's algo to find greatest common divisor.

### CODE REVIEW

**Comment by Rasesh2005** [comment]
Sorry but the logic is incorrect try putting 70,21 as argument it will end up in endless recursion

**Comment by Rasesh2005** [comment]
Fix the issue and i will merge it

**Comment by Adarsh08X** [comment]
> Fix the issue and i will merge it

Can you check once again i tried running it my compiler it's working fine for me.

**Comment by Rasesh2005** [comment]
Ohk my compiler has some issues, nice work

**Pull request merged**
