### PR TITLE
Create DepthFirstSearch.py

### PR DESCRIPTION
**Pull request by abhilashkpy**
DFS Traversal in Python

### CODE REVIEW

**Comment by Rasesh2005** [comment]
Follow Code Conventions as mentioned in README.md pls, Else I cannot Merge Your PR

**Comment by Rasesh2005** [comment]
push all the corrections, and then i will accept your PR

**Comment by Rasesh2005** [comment]
Accepted 💯

**Comment by abhilashkpy** [comment]
Hi,

I have updated the program with necessary changes as per the README.md file.

Regards & Thanks

**Comment by abhilashkpy** [comment]
Dear Sir,

I request you to kindly tell as to how many PRs can I submit in your
repository.
It would be very helpful if we could submit more.

Regards

**Comment by Rasesh2005** [comment]
You Can Submit any number of PR but i cannot accept more than 3 per day i will except next 3 of your PR the next day

**Pull request merged**
