### PR TITLE
Object destructing

### PR DESCRIPTION
**Pull request by VaibhavD74**

### CODE REVIEW

**Comment by Rasesh2005** [comment]
You Call it object Destructing but File name is Object Destructuring.. Check it

**Comment by vaibhav1405** [comment]
commit and filename should be same ?

**Comment by VaibhavD74** [comment]
commit and filename should be same ?

**Comment by Rasesh2005** [comment]
Which One is correct??

**Comment by VaibhavD74** [comment]
ya say which one is correct 
and please if you have access to change then could you please do that

**Comment by Rasesh2005** [comment]
😂 its your contribution bro, how should i know which name is correct ?

**Comment by VaibhavD74** [comment]
This one is correct i added comment for every line https://github.com/Rasesh2005/CP_Snippets/pull/34/commits/d67573494d424cda961c1a670caef550e5148a00

**Pull request merged**
