### PR TITLE
Queue operations

### PR DESCRIPTION
**Pull request by aditioak**
Created folder in C++ and added file Queue Operations using array in C++
Solution to #72

### CODE REVIEW

**Comment by aditioak** [comment]
You told me to add the file in the folder in #77 so I followed your instruction

**Comment by Rasesh2005** [comment]
Yes but you made 2 files of same content one inside folder and one outside , delete the one outside the folder

**Comment by Rasesh2005** [comment]
Check files changed

**Comment by aditioak** [comment]
Changed it! Sorry about the confusion.

**Pull request merged**
