### PR TITLE
added GraphCycleDetection snippet

### PR DESCRIPTION
**Pull request by sidsrivastavasks**

### CODE REVIEW

**Comment by sidsrivastavasks** [comment]
Added GraphCycleDetection Snippet

**Comment by Rasesh2005** [comment]
You need to add multiline commented headers as i have done in the example in README

**Comment by Rasesh2005** [comment]
After completing that i will merge the code

**Comment by sidsrivastavasks** [comment]
Oh right, sorry i forgot.. I'm correcting it right now

**Pull request closed without merging**
