### PR TITLE
Added code to calculate the difference between the sum of 2 diagonals of a square matrix

### PR DESCRIPTION
**Pull request by Deadeye001**
Sample input:
3
11 2 4
4 5 6
10 8 -12

Sample Output:
15

Explanation:
The sum of the elements of the left diagonal = 11+5+(-12) =4
The sum of the elements of the right diagonal = 10+5+4 =19
Hence, the absolute difference= |4-19| = 15.

### CODE REVIEW

**Comment by Rasesh2005** [comment]
Give a Clear Example and explain its solution in description section

**Comment by Deadeye001** [comment]
> Give a Clear Example and explain its solution in description section

Done!
Please check.

**Comment by Rasesh2005** [comment]
i cant see it, can u show me??

**Comment by Rasesh2005** [comment]
also , You will be needed to make a function based  snippet outside main function

**Comment by Deadeye001** [comment]
> i cant see it, can u show me??

I updated the description.
Is it not visible?

**Comment by Deadeye001** [comment]
> also , You will be needed to make a function based snippet outside main functi

**Comment by Rasesh2005** [comment]
> Sample input: 3 11 2 4 4 5 6 10 8 -12
> 
> Sample Output: 15
> 
> Explanation: The sum of the elements of the left diagonal = 11+5+(-12) =4 The sum of the elements of the right diagonal = 10+5+4 =19 Hence, the absolute difference= |4-19| = 15.

Yep Include this Part in your code also along with your Username Date and Description

**Comment by Rasesh2005** [comment]
And Name the file in Padcal case something like DiagonalDifference

**Comment by Deadeye001** [comment]
Done.

**Comment by Rasesh2005** [comment]
Nice work, Thank you for your contribution

**Pull request merged**
