### PR TITLE
Create DetectFloatingPointNumbers.py in python on a problem for detecting floating point numbers

### PR DESCRIPTION
**Pull request by sarthakd999**

### CODE REVIEW

**Comment by Rasesh2005** [comment]
make the program in function packed form, then i will merge it

**Comment by sarthakd999** [comment]
Okk Captain

**Comment by sarthakd999** [comment]
I have done it Please check It And let meknow its correct or not

**Comment by Rasesh2005** [comment]
Dont take input inside function, take input and then pass it to function as parameter

**Pull request merged**
