### PR TITLE
Create BinarySearch.py

### PR DESCRIPTION
**Pull request by AJgthb2002**
resolves issue #16

### CODE REVIEW

**Comment by AJgthb2002** [comment]
please merge this PR

**Comment by Rasesh2005** [comment]
Your application Code is incorrect, Binary Search is applicable for sorted array only but your application example part shows  an unsorted array, fix it ASAP before tonight and i will merge it if i didn't find any mistake

**Comment by AJgthb2002** [comment]
yes, it was a small typo. Put 1 instead of 10. I have fixed it pls check

**Comment by Rasesh2005** [comment]
All Checked and working :)
Merging your PR

**Pull request merged**
